my:
  greeting: welcome to my application! ${app.name}

app:
  name: test profile
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

server:
  port: 9090

management.endpoints.web.exposure.include: "*"